version: "3"

services:
  map:
    # image: overv/openstreetmap-tile-server
    build: ./openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
      - ./openstreetmap-tile-server/osm-updates:/data/updates # edit this line as you like
    ports:
      - "8080:80"
      - "5432:5432"
    environment:
      - THREADS=4
      - "OSM2PGSQL_EXTRA_ARGS=-C 4096"
    command: "run"
  web:
    build:
      context: ./openstreetmap-website
    environment:
      PIDFILE: /tmp/pids/server.pid
    volumes:
      - ./openstreetmap-website:/app
      # Prevent these directories from mounting so they're not shared between host OS and Docker
      - /app/node_modules/
      # Mount a tmp directory that will persist between runs
      - web-tmp:/app/tmp
      # Mount a storage directory that will persist between runs
      - web-storage:/app/storage
    tmpfs:
      /tmp/pids/
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db

  db:
    build:
      context: ./openstreetmap-website
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: openstreetmap
    volumes:
      # Mount the Postgres data directory so it persists between runs
      - db-data:/var/lib/postgresql/data

volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true
  web-tmp:
  web-storage:
  db-data:
